### ISSUE TITLE
Q: What version of VS.Net is required to open this solution?

### ISSUE THREAD

**Issue by mxmissile** [Thraka/SadConsoleEditor#2]
VS 2013 Update 4 says it's (incompatible), I tried the Shared Project Reference Manager extension from here: https://visualstudiogallery.msdn.microsoft.com/315c13a7-2787-4f57-bdf7-adae6ed54450

but no go

thanks

**Comment by Thraka** [comment]
I think the shared project stuff (for non universal apps) is something new to 2015. I didn't realize this, sorry. However, 2015 is amazing and you should really upgrade to it. It's currently free while it's RC.
